version: '3.8'


services:
  kong:
    platform: linux/amd64
    build:
      context: ./docker/kong
    container_name: kong
    depends_on:
      kong_migrations:
        condition: service_completed_successfully
    environment:
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
      - KONG_ADMIN_GUI_PATH=/manager
      - KONG_ADMIN_GUI_URL=http://localhost:8002/manager
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong_db
      - KONG_PG_PASSWORD=kong
      - KONG_PLUGINS=bundled,warden
      - KONG_PLUGINSERVER_NAMES=warden
      - KONG_PLUGINSERVER_WARDEN_START_CMD=/kong/go-plugins/warden
      - KONG_PLUGINSERVER_WARDEN_QUERY_CMD=/kong/go-plugins/warden -dump
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
      - 8002:8002
    command: [ "kong", "start"]
  
  kong_db:
    image: postgres:9.6-alpine
    user: postgres
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
      - POSTGRES_PASSWORD=kong
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 30s
      timeout: 300s
      retries: 5
      start_period: 50s

  kong_migrations:
    platform: linux/amd64
    image: kong:3.3.1-alpine
    command: ["kong", "migrations", "bootstrap"]
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong_db
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kong
    depends_on:
      kong_db:
        condition: service_healthy

  konga:
    image: pantsel/konga:0.14.9
    environment:
      - NODE_ENV=development
      - TOKEN_SECRET=qbsoBD@MHJGM@P^tCw4gW
      - DB_ADAPTER=postgres
      - DB_HOST=kong_db
      - DB_USER=kong
      - DB_PASSWORD=kong
    depends_on:
      kong_db:
        condition: service_healthy
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    ports:
      - 1337:1337
  
  konga_setup:
    image: curlimages/curl:8.2.1
    links:
      - konga
    environment:
      KONGA_EMAIL: kong@konghq.com
      KONGA_USER_NAME: kong
      KONGA_PASSWORD:
    command: >
      curl 'http://konga:1337/register' -H 'Content-Type: application/x-www-form-urlencoded' --data-raw 'username=kong&email=kong%40konghq.com&password=kongkong&password_confirmation=kongkong' --compressed
        
  deck_load:
    image: kong/deck:latest
    links:
      - kong
    volumes: 
      - ./docker/data/kong.yaml:/kong.yaml
    command: ["sync", "--kong-addr", "http://kong:8001"]
  
  people_service:
    build:
      context: ./docker/go-svc
    restart: always
    volumes: 
      - ./docker/data/people.json:/app/people.json
    environment:
      DB_FILE: ./people.json
      PORT: 4001
    ports:
      - 4001:4001
  
